stages:
  - validate
  - security

validate-swarm-architecture:
  stage: validate
  image: docker:24.0.5
  script:
    - echo "Validam sintaxa si structura fisierului de orchestrare..."
    - docker compose config -q
    - echo "Arhitectura Docker Swarm este valida si gata de productie!"

security-check:
  stage: security
  image: alpine:latest
  script:
    - echo "Verificam expunerea porturilor critice..."
    - grep -q "5432:5432" docker-compose.yml && exit 1 || echo "Portul DB este securizat/schimbat corect."